version: "3.8"

services:
  db:
    image: postgres:16.3
    container_name: attendance-db
    environment:
      POSTGRES_DB: attendance-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - attendance-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  attendance-data:
